### ISSUE TITLE
Why is the built bundle so much larger than sanitize-html?

### ISSUE THREAD

**Issue by NullVoxPopuli** [devotox/ember-cli-sanitize-html#19]
https://bundlephobia.com/result?p=ember-cli-sanitize-html@2.0.1
![image](https://user-images.githubusercontent.com/199018/42505832-f68293c2-840d-11e8-95ee-2c3a09a1a064.png)

vs just the sanitize-html library:

![image](https://user-images.githubusercontent.com/199018/42505844-01a43594-840e-11e8-8506-44ca7906685b.png)

ember-cli-sanitize-html somehow has 20kb of additional (gzipped) code?

My whole app.js is 32 kb. :-\

I wonder if ember-cli + broccoli is including tests and such in the final output. :-\

**Comment by NullVoxPopuli** [comment]
I'm also curious how the different sanitizing libraries compare against eachother. For example, `xss` https://bundlephobia.com/result?p=xss@1.0.3 is 5.3kb gzipped, but I wonder if bundling it for the browser would  bloat it.

**Comment by NullVoxPopuli** [comment]
`filthy-clean` https://bundlephobia.com/result?p=filthy-clean@1.0.0 is just 545 _bytes_ gzipped. that's nuts.

**Comment by NullVoxPopuli** [comment]
how does ember-cli-sanitize-html compare with ember-purify? https://www.npmjs.com/package/ember-purify

**Comment by devotox** [comment]
This would most likely just be ember code around sanitize library that is adding the bloat.

Ember purify seems to be a fully thought out top down approach while this is merely a wrapper around sanitize html
